# Generated by Django 4.1.2 on 2022-10-26 14:52
from __future__ import unicode_literals

from django.db import migrations
from django.utils.text import slugify

def slugify_title(apps, schema_editor):
    Resource = apps.get_model('shelf', 'Resource')
    for resource in Resource.objects.all():
        resource.slug = slugify(Resource.title)
        resource.save()

class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_resource'),
    ]

    operations = [
        migrations.RunPython(slugify_title),
    ]
